### PR TITLE
375 fix/greater than option not working

### LINKED ISSUE #375: [By User Meta] "Greater than" option not working as expected
Blocks #303 

Meta Key/value

image

User Module

image

image

image

image

### LINKED ISSUE #376: [By User Meta] "Greater than or equal to" option not working as expected
Blocks #303 

Use the same steps as #375 to replicate but make to choose the option as "Greater than or equal to".

### LINKED ISSUE #405: [Delete User Meta] Functionality not working as expected

### PR DESCRIPTION
**Pull request by mariadanieldeepak**
This PR was originally created to fix #375 and to fix #376

But this one now fixes #405

### CODE REVIEW

**Comment by sudar** [comment]
@mariadanieldeepak 

Currently there is a conflict. Fix the conflict by getting the latest from `dev/6.0.0` and merge it into your branch.

Let's do the review once the merge conflict is resolved.

**Comment by mariadanieldeepak** [comment]
@sudar, 

> Let's do the review once the merge conflict is resolved.

Resolved conflicts.

**Comment by sudar** [comment]
@mariadanieldeepak 

Did you checked the `Files Changed` tab of this PR? ;)

**Comment by mariadanieldeepak** [comment]
Closing this as there are no file changes.

**Pull request closed without merging**
