### PR TITLE
PR: Remove unnecessary td tags

### LINKED ISSUE #737: Remove unwanted <td> from render_limit_settings
Bulk delete from trash addon had problems while adding limit filter. 
Please refer https://github.com/sudar/bulk-delete-from-trash/issues/13

### PR DESCRIPTION
**Pull request by esudalaimadan**
Fix #737

### CODE REVIEW

**Comment by sudar** [comment]
@esudalaimadan 

I have fixed the failing StyleCi issues.

Have you tested how the other modules/add-ons look with this change? Can you post screenshots of some of them?

**Comment by esudalaimadan** [comment]
These are the screenshots taken with the new code(i.e., after removing <td>)
Screenshot from 2020-08-17 12-50-36
Screenshot from 2020-08-17 12-50-27
Screenshot from 2020-08-17 12-50-01

**Comment by esudalaimadan** [comment]
**These are the screenshots with dev/6.1.0:**
Screenshot from 2020-08-17 12-58-24
Screenshot from 2020-08-17 12-58-15

**Comment by esudalaimadan** [comment]
In base plugin, all modules look good.  I have taken screenshot of few addons and attached them here.

**Review by sudar — APPROVED** [review]

**Pull request merged**
